### ISSUE TITLE
Codegen needs to trim Strings when read from the config files

### ISSUE THREAD

**Issue by ddobrin** [networknt/light-codegen#212]
When Codegen reads the config.json file, some fields are read as strings. These strings need to be trimmed.

Without this, issue #208 is affected:
https://github.com/networknt/light-codegen/issues/208

Developers can declare values as:
"httpPort":8080,
or
"httpPort": 8080, (see a space in the middle).

Issue listed in #208 would generate differently and fail for 
httpPort: ${server.httpPort:@httpPort}

The Config module fails if it sees:
httpPort: ${server.httpPort:8080}
vs
httpPort: ${server.httpPort: 8080} (again, see space)

**Comment by stevehu** [comment]
I think this issue has been resolved by https://github.com/networknt/light-codegen/pull/218
@ddobrin @jiachen1120 Could you please confirm? Thanks.

**Comment by jiachen1120** [comment]
@stevehu Hi, I think compared with trim the value, we should ban user to add space after the colon, and only one way for users to declare. Since even though JSON can parse ${server.httpPort: 8080} but YAML cannot, and an exception will be thrown by snakeyaml when adding a space there. I think to keep them in the same rule, space should not appear here.  What do you think? Thanks

**Comment by stevehu** [comment]
@jiachen1120 Makes sense. You are the decision maker. Thanks.

**Comment by ddobrin** [comment]
PR #218 fixes the issue.
