### ISSUE TITLE
generate code on win10 got error

### ISSUE THREAD

**Issue by jang675953** [networknt/light-codegen#259]
generate code on win10 got error,it can not generate code 
![image](https://user-images.githubusercontent.com/20883097/55406022-dd1e2200-558d-11e9-8441-672b326227e5.png)

**Comment by jang675953** [comment]
java version is oracle 8u201
![image](https://user-images.githubusercontent.com/20883097/55406209-3e45f580-558e-11e9-97f0-ca26df92e6cf.png)

**Comment by stevehu** [comment]
In the last release, we have added the maven wrapper to the generated project so that users won't need to install Maven locally to build the project. The wrapper has to commands, one for Linux and one for Windows. On Linux/Mac/Unit/BSD system, the mvnw needs to be updated to change the mode to the executable so that it can be invoked from the terminal. The Java code we used doesn't support Windows and the update mode failed with the above exception. We need to detect the running environment and skip this update for Windows system. @jang675953 Thanks a lot for bringing it up.

**Comment by stevehu** [comment]
For the stacktrace, it looks like the exception happens before the setExecutable in the transfer method. 

```
        transfer("/maven/mvnw", targetPath, "", "mvnw");
        setExecutable(Paths.get(targetPath, "mvnw").toString());
```

I don't have Windows system available and @BalloonWen will to reproduce and fix it on his Windows laptop.

**Comment by jang675953** [comment]
Ok,lastnight,i delete the code you show,It go The same error

**Comment by stevehu** [comment]
The problem is deep in the JDK and only Windows is impacted. Here are several links: 

https://stackoverflow.com/questions/33924479/java-nio-file-filesystemexception-the-process-cannot-access-the-file-because-it

https://stackoverflow.com/questions/40779633/java-the-process-cannot-access-the-file-because-it-is-being-used-by-another-pr

https://github.com/SeleniumHQ/selenium/issues/4251

**Comment by stevehu** [comment]
@jang675953 I have commented out the wrapper transfer for three generators. There are still test case failures due to Windows path if different than Linux and Mac. I have opened another issue to address the test cases. https://github.com/networknt/light-codegen/issues/265

If you want to compile the generator on your Windows machine, please use `mvn clean install -DskipTests'

sorry for the inconvenience.
