### ISSUE TITLE
decryptor module is missing in the generated pom.xml file

### ISSUE THREAD

**Issue by chenyan71** [networknt/light-codegen#300]
in the codegen, the config.xml need the decryptor module dependency in the pom file
${config.decryptorClass:com.networknt.decrypt.AESDecryptor}

**Comment by stevehu** [comment]
There is an additional issue with the config.yml file generation. The config.yml needs to be in the 

```
  "generateEnvVars": {
    "generate": true,
    "skipArray": true,
    "skipMap": true,
    "exclude": [
      "handerl.yml",
      "values.yml",
      "config.yml"
    ]
  }

```
in the config.json file as the input for the light-codegen. This is not acceptable as existing users won't know to add this section correctly. We need somehow make it as a default. Or we can manually update the template instead of using the YAMLFileParameterizer class blindly.

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [decryptor module is missing in the generated pom.xml file](https://trello.com/c/E6HdUFMk/220-decryptor-module-is-missing-in-the-generated-pomxml-file)
